"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { BrowserMultiFormatReader } from "@zxing/browser";
import { APPEARANCE_PROTECTION, APPEARANCE_PROTECTION_RATE, BASE_SERVICE_OPTIONS, BASE_SERVICE_RATES } from "../lib/pricing";
import InvoicePanel from "./invoice-panel";

type Location = { id: number; name: string };
type Job = { id: string; locationId: number; completedAt: string; stockOrVin: string; vehicle: string; technicianName: string; damageNotes: string; service: string; baseAmount: number; addOnAmount: number; purchaseOrderNumber: string | null; repairOrderNumber: string | null; purchaseOrderUrl: string | null; archiveUrl: string | null };
type VerificationStatus = "ready" | "needs_review" | "approved" | "skipped";
type VerificationItem = { id: string; createdAt: string; sourceIdentifier: string; purchaseOrderNumber: string; repairOrderNumber: string | null; matchedJobId: string | null; candidateJobIds: string[]; matchMethod: string; status: VerificationStatus; matchedJob: Job | null };
type BatchEntry = { purchaseOrderNumber: string; repairOrderNumber: string; sourceIdentifier: string };
type AuditEvent = { id: string; jobId: string; createdAt: string; eventType: string; actorEmail: string; actorName: string; reason: string | null; beforeValue: string | null; afterValue: string };
type View = "manager" | "technician";
type Role = "manager" | "technician";
type Member = { role: Role; displayName: string; email: string };
type StaffMember = Member & { active: boolean };
type Period = "week" | "month" | "year";
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const TECHNICIAN_LOCATION_STORAGE_KEY = "titan-technician-location";
function normalizeVehicleId(value: string) { const cleaned = value.toUpperCase().replace(/[^A-Z0-9]/g, ""); return /^I[A-HJ-NPR-Z0-9]{17}$/.test(cleaned) ? cleaned.slice(1) : cleaned; }
function csvValue(value: string | number | null | undefined) { const text = String(value ?? ""); return `"${text.replace(/"/g, '""')}"`; }
function escapeHtml(value: string | number | null | undefined) { return String(value ?? "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character); }
function blankBatchRows(count = 6): BatchEntry[] { return Array.from({ length: count }, () => ({ purchaseOrderNumber: "", repairOrderNumber: "", sourceIdentifier: "" })); }

export default function Home() {
  const [jobs, setJobs] = useState<Job[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [locationId, setLocationId] = useState<number | "all">("all"); const [member, setMember] = useState<Member | null>(null); const [role, setRole] = useState<Role | null>(null); const [authReady, setAuthReady] = useState(false); const [view, setView] = useState<View>("technician"); const [period, setPeriod] = useState<Period>("week"); const [intakeOpen, setIntakeOpen] = useState(false); const [locationOpen, setLocationOpen] = useState(false); const [managerOpen, setManagerOpen] = useState(false); const [verificationOpen, setVerificationOpen] = useState(false); const [verificationImportOpen, setVerificationImportOpen] = useState(false); const [invoicesOpen, setInvoicesOpen] = useState(false); const [verificationItems, setVerificationItems] = useState<VerificationItem[]>([]); const [batchRows, setBatchRows] = useState<BatchEntry[]>(() => blankBatchRows()); const [staffOpen, setStaffOpen] = useState(false); const [staff, setStaff] = useState<StaffMember[]>([]); const [staffName, setStaffName] = useState(""); const [staffEmail, setStaffEmail] = useState(""); const [staffPassword, setStaffPassword] = useState(""); const [staffRole, setStaffRole] = useState<Role>("technician"); const [historyOpen, setHistoryOpen] = useState(false); const [historyJob, setHistoryJob] = useState<Job | null>(null); const [auditEvents, setAuditEvents] = useState<AuditEvent[]>([]); const [cameraOpen, setCameraOpen] = useState(false); const [cameraError, setCameraError] = useState(""); const [managerJobId, setManagerJobId] = useState(""); const [purchaseOrderNumber, setPurchaseOrderNumber] = useState(""); const [repairOrderNumber, setRepairOrderNumber] = useState(""); const [correctionReason, setCorrectionReason] = useState(""); const [stock, setStock] = useState(""); const [vehicle, setVehicle] = useState(""); const [technicianName, setTechnicianName] = useState(""); const [damageNotes, setDamageNotes] = useState(""); const [selectedServices, setSelectedServices] = useState<string[]>(["New Honda Detail"]); const [newLocation, setNewLocation] = useState(""); const [message, setMessage] = useState(""); const videoRef = useRef<HTMLVideoElement>(null);

  async function refresh() { const [locationsResponse, jobsResponse] = await Promise.all([fetch("/api/locations"), fetch("/api/jobs")]); if (!locationsResponse.ok || !jobsResponse.ok) { setMessage("Your secure data connection is not ready yet. Try again after publishing."); return; } const locationData = await locationsResponse.json() as { locations: Location[] }; const jobData = await jobsResponse.json() as { jobs: Job[] }; setLocations(locationData.locations); setLocationId((current) => { if (current !== "all") return current; const rememberedId = Number(window.localStorage.getItem(TECHNICIAN_LOCATION_STORAGE_KEY)); const remembered = locationData.locations.find((item) => item.id === rememberedId); return remembered?.id ?? (locationData.locations.length === 1 ? locationData.locations[0].id : current); }); setJobs(jobData.jobs); }
  useEffect(() => { fetch("/api/me").then((response) => response.ok ? response.json() : null).then((data: { member?: Member } | null) => { if (data?.member) { setMember(data.member); setRole(data.member.role); setTechnicianName(data.member.displayName || data.member.email); setView(data.member.role === "manager" ? "manager" : "technician"); void refresh(); } }).finally(() => setAuthReady(true)); }, []);
  useEffect(() => { if (role === "technician" && typeof locationId === "number") window.localStorage.setItem(TECHNICIAN_LOCATION_STORAGE_KEY, String(locationId)); }, [locationId, role]);
  useEffect(() => {
    if (!cameraOpen) return;
    let active = true; let controls: { stop: () => void } | undefined;
    const start = async () => {
      try {
        if (!navigator.mediaDevices?.getUserMedia || !videoRef.current) throw new Error("Camera access is not available on this device.");
        const reader = new BrowserMultiFormatReader(undefined, { delayBetweenScanAttempts: 180 });
        controls = await reader.decodeFromConstraints({ video: { facingMode: { ideal: "environment" }, width: { ideal: 1920 }, height: { ideal: 1080 } }, audio: false }, videoRef.current, (result) => { if (result && active) { setStock(normalizeVehicleId(result.getText())); setCameraOpen(false); } });
      } catch (error) { setCameraError(error instanceof Error ? error.message : "Unable to start the camera scanner."); }
    };
    void start();
    return () => { active = false; controls?.stop(); };
  }, [cameraOpen]);
  const [searchQuery, setSearchQuery] = useState("");
  const visible = useMemo(() => jobs.filter((job) => locationId === "all" || job.locationId === locationId), [jobs, locationId]);
  const displayedJobs = useMemo(() => { const query = searchQuery.trim().toLowerCase(); if (!query) return visible; return visible.filter((job) => job.stockOrVin.toLowerCase().includes(query) || (job.vehicle || "").toLowerCase().includes(query) || (job.technicianName || "").toLowerCase().includes(query) || job.service.toLowerCase().includes(query)); }, [visible, searchQuery]); const periodStart = useMemo(() => { const start = new Date(); start.setHours(0, 0, 0, 0); if (period === "week") { const offset = (start.getDay() + 6) % 7; start.setDate(start.getDate() - offset); } else if (period === "month") start.setDate(1); else { start.setMonth(0, 1); } return start; }, [period]); const periodJobs = useMemo(() => visible.filter((job) => new Date(job.completedAt) >= periodStart), [visible, periodStart]); const missing = visible.filter((job) => !job.purchaseOrderNumber && !job.purchaseOrderUrl); const baseRevenue = periodJobs.reduce((sum, job) => sum + job.baseAmount, 0); const addOnRevenue = periodJobs.reduce((sum, job) => sum + job.addOnAmount, 0); const revenue = baseRevenue + addOnRevenue; const technicianTotals = useMemo(() => Object.values(periodJobs.reduce<Record<string, { name: string; jobs: number; base: number; addOn: number }>>((totals, job) => { const name = job.technicianName || "Unassigned"; const current = totals[name] ?? { name, jobs: 0, base: 0, addOn: 0 }; current.jobs += 1; current.base += job.baseAmount; current.addOn += job.addOnAmount; totals[name] = current; return totals; }, {})).sort((a, b) => (b.base + b.addOn) - (a.base + a.addOn) || b.jobs - a.jobs), [periodJobs]); const periodLabel = period === "week" ? "This week" : period === "month" ? "This month" : "This year"; const selectedLocation = locationId === "all" ? undefined : locations.find((item) => item.id === locationId);

  async function saveJob(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const vehicleId = normalizeVehicleId(stock); if (!vehicleId || !selectedLocation || !technicianName.trim() || !selectedServices.length) { setMessage("Choose a location, technician, and service before saving."); return; } const response = await fetch("/api/jobs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ locationId: selectedLocation.id, stockOrVin: vehicleId, vehicle, technicianName, damageNotes, services: selectedServices }) }); if (!response.ok) { setMessage("That completed detail could not be saved. Please try again."); return; } setStock(""); setVehicle(""); setDamageNotes(""); setIntakeOpen(false); setMessage(""); await refresh(); }
  async function saveLocation(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/locations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: newLocation }) }); if (!response.ok) { setMessage("That location already exists or could not be saved."); return; } const data = await response.json() as { location: Location }; setLocations((current) => [...current, data.location].sort((a, b) => a.name.localeCompare(b.name))); setLocationId(data.location.id); setNewLocation(""); setLocationOpen(false); setMessage(""); }
  async function openStaff() { const response = await fetch("/api/staff"); if (!response.ok) { setMessage("Staff records could not be loaded."); return; } const data = await response.json() as { members: StaffMember[] }; setStaff(data.members); setStaffOpen(true); }
  async function saveStaff(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/staff", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ displayName: staffName, email: staffEmail, role: staffRole, password: staffPassword }) }); const data = await response.json().catch(() => null) as { member?: StaffMember; error?: string } | null; if (!response.ok || !data?.member) { setMessage(data?.error ?? "That staff member could not be saved."); return; } setStaff((current) => [...current.filter((item) => item.email !== data.member?.email), data.member!].sort((a, b) => a.displayName.localeCompare(b.displayName))); setStaffName(""); setStaffEmail(""); setStaffPassword(""); setStaffRole("technician"); setMessage("Staff account saved. Share their password directly with them."); }
  async function signOut() { await fetch("/api/auth/logout", { method: "POST" }); setMember(null); setRole(null); setJobs([]); setLocations([]); setAuthReady(true); }
  function openManager(job?: Job) { const chosen = job ?? missing[0] ?? visible[0]; if (!chosen) { setMessage("There are no completed jobs to manage yet."); return; } setManagerJobId(chosen.id); setPurchaseOrderNumber(chosen.purchaseOrderNumber ?? ""); setRepairOrderNumber(chosen.repairOrderNumber ?? ""); setCorrectionReason(""); setManagerOpen(true); }
  function chooseManagerJob(id: string) { const chosen = visible.find((job) => job.id === id); if (!chosen) return; setManagerJobId(id); setPurchaseOrderNumber(chosen.purchaseOrderNumber ?? ""); setRepairOrderNumber(chosen.repairOrderNumber ?? ""); setCorrectionReason(""); }
  async function refreshVerification() { const response = await fetch("/api/po-verification"); if (!response.ok) { setMessage("The PO verification queue could not be loaded."); return; } const data = await response.json() as { items: VerificationItem[] }; setVerificationItems(data.items); }
  async function openVerification() { await refreshVerification(); setVerificationOpen(true); }
  function updateBatchRow(index: number, field: keyof BatchEntry, value: string) { setBatchRows((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, [field]: value } : row)); }
  function removeBatchRow(index: number) { setBatchRows((rows) => rows.length === 1 ? blankBatchRows(1) : rows.filter((_, rowIndex) => rowIndex !== index)); }
  async function importVerificationBatch(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const populatedRows = batchRows.filter((row) => row.purchaseOrderNumber.trim() || row.repairOrderNumber.trim() || row.sourceIdentifier.trim()); if (!populatedRows.length || populatedRows.some((row) => !row.purchaseOrderNumber.trim() || !row.sourceIdentifier.trim())) { setMessage("Each entered row needs a PO number and a stock number or VIN. RO is optional."); return; } const batchText = populatedRows.map((row) => [row.purchaseOrderNumber, row.repairOrderNumber, row.sourceIdentifier].join("\t")).join("\n"); const response = await fetch("/api/po-verification", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ batchText }) }); const data = await response.json().catch(() => null) as { imported?: number; ready?: number; needsReview?: number; error?: string } | null; if (!response.ok) { setMessage(data?.error ?? "That PO batch could not be read."); return; } setBatchRows(blankBatchRows()); setVerificationImportOpen(false); await refreshVerification(); setVerificationOpen(true); setMessage(`${data?.imported ?? 0} PO${data?.imported === 1 ? "" : "s"} staged: ${data?.ready ?? 0} ready to attach, ${data?.needsReview ?? 0} to review.`); }
  async function reviewVerificationItem(id: string, action: "approve" | "skip") { const response = await fetch("/api/po-verification", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, action }) }); const data = await response.json().catch(() => null) as { error?: string } | null; if (!response.ok) { setMessage(data?.error ?? "That queue item could not be updated."); return false; } await Promise.all([refreshVerification(), refresh()]); return true; }
  async function approveReadyMatches() { const ready = verificationItems.filter((item) => item.status === "ready"); if (!ready.length) { setMessage("There are no uniquely matched PO rows ready to attach."); return; } const results = await Promise.all(ready.map((item) => reviewVerificationItem(item.id, "approve"))); const count = results.filter(Boolean).length; setMessage(`${count} PO${count === 1 ? "" : "s"} attached. Any remaining items need review.`); }
  function chooseBaseService(value: string) { setSelectedServices((current) => [...current.filter((item) => item === APPEARANCE_PROTECTION), value]); }
  function toggleAppearanceProtection() { setSelectedServices((current) => current.includes(APPEARANCE_PROTECTION) ? current.filter((item) => item !== APPEARANCE_PROTECTION) : [...current, APPEARANCE_PROTECTION]); }
  async function saveManagerRecord(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/jobs", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: managerJobId, purchaseOrderNumber, repairOrderNumber, correctionReason }) }); if (!response.ok) { const data = await response.json().catch(() => null) as { error?: string } | null; setMessage(data?.error ?? "The PO and RO could not be saved. Please try again."); return; } setManagerOpen(false); setMessage(""); await refresh(); }
  async function openHistory(job: Job) { setHistoryJob(job); setAuditEvents([]); setHistoryOpen(true); const response = await fetch(`/api/jobs?auditJobId=${encodeURIComponent(job.id)}`); if (!response.ok) { setMessage("The audit history could not be loaded. Please try again."); return; } const data = await response.json() as { events: AuditEvent[] }; setAuditEvents(data.events); }
  function downloadManagerCsv() { const rows = [["Period", "Technician", "Vehicles", "Base revenue", "Add-on revenue", "Total revenue"], ...technicianTotals.map((item) => [periodLabel, item.name, item.jobs, item.base, item.addOn, item.base + item.addOn])]; const file = new Blob([rows.map((row) => row.map(csvValue).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(file); link.download = `titan-${period}-technician-totals.csv`; link.click(); URL.revokeObjectURL(link.href); }
  function printMissingPurchaseOrders() { const printWindow = window.open("", "titan-po-list", "noopener,noreferrer"); if (!printWindow) { setMessage("Your browser blocked the print window. Allow pop-ups and try again."); return; } const rows = missing.map((job) => `<tr><td>${escapeHtml(job.stockOrVin)}</td><td>${escapeHtml(job.vehicle || "—")}</td><td>${escapeHtml(job.technicianName || "—")}</td><td>${escapeHtml(job.service)}</td><td>${escapeHtml(locations.find((item) => item.id === job.locationId)?.name ?? "Location")}</td></tr>`).join("") || "<tr><td colspan=\"5\">No missing purchase orders.</td></tr>"; printWindow.document.write(`<!doctype html><title>Missing Purchase Orders</title><style>body{font-family:Arial,sans-serif;color:#14213d;padding:28px}h1{margin:0}p{color:#667085}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{padding:10px;text-align:left;border-bottom:1px solid #dbe2ea;font-size:13px}th{background:#f4f6f8}@media print{body{padding:0}}</style><h1>Missing Purchase Orders</h1><p>${escapeHtml(periodLabel)} · ${escapeHtml(locationId === "all" ? "All locations" : selectedLocation?.name)} · ${new Date().toLocaleDateString()}</p><table><thead><tr><th>Stock / VIN</th><th>Vehicle</th><th>Technician</th><th>Service</th><th>Location</th></tr></thead><tbody>${rows}</tbody></table>`); printWindow.document.close(); printWindow.focus(); printWindow.print(); }
  function printVerificationQueue() { const printWindow = window.open("", "titan-po-verification", "noopener,noreferrer"); if (!printWindow) { setMessage("Your browser blocked the print window. Allow pop-ups and try again."); return; } const pending = verificationItems.filter((item) => item.status === "ready" || item.status === "needs_review"); const rows = pending.map((item) => `<tr><td>${escapeHtml(item.status === "ready" ? "READY" : "REVIEW")}</td><td>${escapeHtml(item.purchaseOrderNumber)}</td><td>${escapeHtml(item.repairOrderNumber || "—")}</td><td>${escapeHtml(item.sourceIdentifier)}</td><td>${escapeHtml(item.matchedJob?.stockOrVin || "—")}</td><td>${escapeHtml(item.matchedJob?.vehicle || item.matchMethod)}</td></tr>`).join("") || "<tr><td colspan=\"6\">No PO items are awaiting verification.</td></tr>"; printWindow.document.write(`<!doctype html><title>PO Verification Queue</title><style>body{font-family:Arial,sans-serif;color:#14213d;padding:28px}h1{margin:0}p{color:#667085}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{padding:10px;text-align:left;border-bottom:1px solid #dbe2ea;font-size:12px}th{background:#f4f6f8}.review{color:#9a5b00;font-weight:bold}@media print{body{padding:0}}</style><h1>PO / RO Verification Queue</h1><p>Print date: ${new Date().toLocaleDateString()} · ${pending.length} item${pending.length === 1 ? "" : "s"} awaiting action</p><table><thead><tr><th>Status</th><th>PO</th><th>RO</th><th>Entered stock / VIN</th><th>Matched stock / VIN</th><th>Vehicle / match note</th></tr></thead><tbody>${rows}</tbody></table>`); printWindow.document.close(); printWindow.focus(); printWindow.print(); }

  if (!authReady) return <main className="sign-in-shell"><p className="eyebrow">TITAN AUTO SPA</p><h1>Loading your secure workspace…</h1></main>;
  if (!member) return <LoginScreen onSignedIn={(signedInMember) => { setMember(signedInMember); setRole(signedInMember.role); setTechnicianName(signedInMember.displayName || signedInMember.email); setView(signedInMember.role === "manager" ? "manager" : "technician"); void refresh(); }} />;
  return <main><header className="topbar"><div className="brand"><b>T</b><span>Titan Operations</span></div><div className="view-tabs"><button className={view === "technician" ? "selected" : ""} onClick={() => setView("technician")}>Technician view</button>{role === "manager" && <button className={view === "manager" ? "selected" : ""} onClick={() => setView("manager")}>Manager view</button>}<button className="sign-out" onClick={() => void signOut()}>Sign out</button></div></header>
    <section className="hero"><div><p className="eyebrow">{view === "manager" ? "MANAGER CONTROL CENTER" : "TECHNICIAN WORKSPACE"}</p><h1>{view === "manager" ? "Control the paperwork without slowing the work." : "Finish the detail. Record it. Move to the next car."}</h1><p>{view === "manager" ? "Review completed work, enter PO and RO numbers, and resolve billing exceptions by location." : "Record completed details with the vehicle, service, and your name. PO and RO paperwork stays with management."}</p></div><div className="actions">{view === "manager" && <><button className="secondary" onClick={() => setLocationOpen(true)}>+ Add location</button><button className="secondary" onClick={() => void openStaff()}>Manage staff</button><button className="secondary" onClick={() => setInvoicesOpen(true)}>Invoices</button></>}<button className="primary" onClick={() => setIntakeOpen(true)}>{view === "manager" ? "+ New completed job" : "+ Complete a vehicle"}</button></div></section>
    <nav className="filters"><button className={locationId === "all" ? "selected" : ""} onClick={() => setLocationId("all")}>All locations</button>{locations.map((item) => <button key={item.id} className={locationId === item.id ? "selected" : ""} onClick={() => setLocationId(item.id)}>{item.name}</button>)}</nav>
    {view === "manager" && <nav className="period-filters" aria-label="Revenue period"><span>Revenue period</span>{(["week", "month", "year"] as Period[]).map((item) => <button key={item} className={period === item ? "selected" : ""} onClick={() => setPeriod(item)}>{item === "week" ? "Weekly" : item === "month" ? "Monthly" : "Yearly"}</button>)}</nav>}
    <section className="metrics">{view === "manager" ? <><Metric label={`${periodLabel} completed`} value={String(periodJobs.length)} note="timestamped details"/><Metric label={`${periodLabel} base revenue`} value={money.format(baseRevenue)} note="detail services"/><Metric label={`${periodLabel} add-on revenue`} value={money.format(addOnRevenue)} note="appearance protection"/><Metric label={`${periodLabel} total revenue`} value={money.format(revenue)} note="base + protection"/></> : <Metric label="Vehicles completed today" value={String(visible.length)} note="your location’s count"/>}</section>
    <section className="grid"><section className="panel"><div className="heading"><div><p className="eyebrow">{view === "manager" ? "COMPLETED JOBS" : "TODAY’S COMPLETED DETAILS"}</p><h2>{view === "manager" ? "Live work ledger" : "Your work is recorded"}</h2></div><span>{displayedJobs.length} jobs</span></div><input className="job-search" type="search" value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} placeholder="Search by stock #, VIN, vehicle, or technician" /><div className="jobs">{displayedJobs.map((job) => <article className="job" key={job.id}><time>{new Date(job.completedAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</time><div><strong>{job.stockOrVin}</strong><small>{job.vehicle || "Vehicle details pending"} · {job.service}{job.technicianName ? ` · ${job.technicianName}` : ""}{view === "manager" && job.damageNotes ? " · Damage noted" : ""}</small>{view === "manager" && job.damageNotes && <small className="damage-note">Damage: {job.damageNotes}</small>}</div><span className="location">{locations.find((item) => item.id === job.locationId)?.name ?? "Location"}</span>{view === "manager" && <strong>{money.format(job.baseAmount + job.addOnAmount)}</strong>}{view === "manager" ? <div className="job-actions"><button className={job.purchaseOrderNumber || job.purchaseOrderUrl ? "po-saved" : "po-missing"} onClick={() => openManager(job)}>{job.purchaseOrderNumber || job.purchaseOrderUrl ? `PO ${job.purchaseOrderNumber ?? "attached"}` : "Enter PO / RO"}</button><button className="history" onClick={() => void openHistory(job)}>History</button></div> : <span className="detail-done">Detail complete</span>}</article>)}{!displayedJobs.length && <p className="empty">{searchQuery ? "No completed details match that search." : "No completed details in this view yet."}</p>}</div></section>
    {view === "manager" ? <aside className="panel"><p className="eyebrow">TECHNICIAN TOTALS</p><h2>{periodLabel} scoreboard</h2><p className="muted">Vehicle count and revenue by technician. Only managers can see this.</p><div className="technician-totals">{technicianTotals.map((technician) => <article key={technician.name}><strong>{technician.name}</strong><span>{technician.jobs} vehicles</span><b>{money.format(technician.base + technician.addOn)}</b><small>{money.format(technician.base)} base · {money.format(technician.addOn)} add-on</small></article>)}{!technicianTotals.length && <p className="empty">No completed jobs in this period yet.</p>}</div><button className="secondary" onClick={downloadManagerCsv}>Download technician totals</button><div className="control-section"><p className="eyebrow">PURCHASE ORDER CONTROL</p><h2>Cars without a purchase order</h2><p className="muted">Paste the dealer’s PO list, glance over proposed matches, then approve and print from one verification queue.</p>{missing.map((job) => <button className="missing" onClick={() => openManager(job)} key={job.id}><strong>{job.stockOrVin}</strong><small>{locations.find((item) => item.id === job.locationId)?.name ?? "Location"}</small></button>)}{!missing.length && <p className="empty">Nothing is waiting for a purchase order.</p>}<button className="secondary" onClick={() => setVerificationImportOpen(true)}>Paste PO / RO batch</button><button className="secondary" onClick={() => void openVerification()}>Open verification queue</button><button className="secondary" onClick={printMissingPurchaseOrders}>Print missing-PO list</button><button className="secondary" onClick={() => openManager()}>Single PO / RO entry</button></div><div className="pricing-list"><p className="eyebrow">CURRENT PRICING</p>{BASE_SERVICE_OPTIONS.map((service) => <p key={service}><span>{service}</span><strong>{money.format(BASE_SERVICE_RATES[service])}</strong></p>)}<p><span>{APPEARANCE_PROTECTION}</span><strong>{money.format(APPEARANCE_PROTECTION_RATE)}</strong></p></div></aside> : <aside className="panel"><p className="eyebrow">TECHNICIAN FLOW</p><h2>That’s all you need to do.</h2><p className="muted">When the detail is finished, scan the vehicle, choose the work performed, then save. This device remembers its location. Management handles the PO, RO, invoice packet, and exception follow-up.</p><button className="secondary" onClick={() => setIntakeOpen(true)}>Record completed detail</button></aside>}</section>
    {message && <p className="notice">{message}</p>}
    <InvoicePanel open={invoicesOpen} onClose={() => setInvoicesOpen(false)} locations={locations} onMessage={setMessage} />
    {locationOpen && <div className="backdrop"><form className="intake" onSubmit={saveLocation}><button aria-label="Close" type="button" className="close" onClick={() => setLocationOpen(false)}>×</button><p className="eyebrow">NEW LOCATION</p><h2>Add a location once.</h2><p>Its completed jobs, billing, and packet history stay separated from every other location.</p><label>Location name<input autoFocus required value={newLocation} onChange={(e) => setNewLocation(e.target.value)} placeholder="Honda San Francisco" /></label><button className="primary" type="submit">Add location</button></form></div>}
    {staffOpen && <div className="backdrop"><section className="intake staff-card"><button aria-label="Close staff management" type="button" className="close" onClick={() => setStaffOpen(false)}>×</button><p className="eyebrow">STAFF ACCESS</p><h2>Create or reset a staff password.</h2><p>Enter an existing email again to reset that person’s password. Passwords stay private—share them directly with the team member.</p><form onSubmit={saveStaff}><label>Name<input autoFocus required value={staffName} onChange={(e) => setStaffName(e.target.value)} placeholder="Alex" /></label><label>Email<input required type="email" value={staffEmail} onChange={(e) => setStaffEmail(e.target.value)} placeholder="alex@example.com" /></label><label>Role<select value={staffRole} onChange={(e) => setStaffRole(e.target.value as Role)}><option value="technician">Technician</option><option value="manager">Manager</option></select></label><label>Password<input required type="password" autoComplete="new-password" minLength={8} maxLength={128} value={staffPassword} onChange={(e) => setStaffPassword(e.target.value)} placeholder="At least 8 characters" /></label><button className="primary" type="submit">Save staff password</button></form><div className="staff-list">{staff.map((item) => <article key={item.email}><strong>{item.displayName || item.email}</strong><small>{item.email} · {item.role}</small></article>)}</div></section></div>}
    {managerOpen && <div className="backdrop"><form className="intake" onSubmit={saveManagerRecord}><button aria-label="Close" type="button" className="close" onClick={() => setManagerOpen(false)}>×</button><p className="eyebrow">MANAGER VIEW</p><h2>Enter PO and RO.</h2><p>Use this after detail is completed and the dealership provides the paper purchase order. Changes to a saved number require a reason.</p><label>Completed car<select value={managerJobId} onChange={(e) => chooseManagerJob(e.target.value)} required>{visible.map((job) => <option key={job.id} value={job.id}>{job.stockOrVin} · {job.vehicle || job.service}</option>)}</select></label><label>Purchase order number<input autoFocus required value={purchaseOrderNumber} onChange={(e) => setPurchaseOrderNumber(e.target.value)} placeholder="PO number" /></label><label>Repair order number<input value={repairOrderNumber} onChange={(e) => setRepairOrderNumber(e.target.value)} placeholder="RO number (optional)" /></label><label>Correction reason <span className="optional">(required only when changing a saved PO or RO)</span><input value={correctionReason} onChange={(e) => setCorrectionReason(e.target.value)} placeholder="Why was this number changed?" /></label><button className="primary" type="submit">Save PO / RO</button></form></div>}
    {verificationImportOpen && <div className="backdrop"><form className="intake verification-card" onSubmit={importVerificationBatch}><button aria-label="Close batch PO entry" type="button" className="close" onClick={() => setVerificationImportOpen(false)}>×</button><p className="eyebrow">BATCH PO / RO ENTRY</p><h2>Enter the dealer paperwork.</h2><p>Use one row per vehicle. PO and Stock/VIN are required; RO is optional. Add as many rows as you need, then build the verification queue.</p><div className="batch-entry-grid"><div className="batch-entry-head"><span>PO number *</span><span>RO number</span><span>Stock number / VIN *</span><span /></div>{batchRows.map((row, index) => <div className="batch-entry-row" key={index}><input autoFocus={index === 0} required={index === 0} aria-label={`Row ${index + 1} purchase order number`} value={row.purchaseOrderNumber} onChange={(event) => updateBatchRow(index, "purchaseOrderNumber", event.target.value)} placeholder="PO number" /><input aria-label={`Row ${index + 1} repair order number`} value={row.repairOrderNumber} onChange={(event) => updateBatchRow(index, "repairOrderNumber", event.target.value)} placeholder="RO (optional)" /><input required={index === 0} autoCapitalize="characters" aria-label={`Row ${index + 1} stock number or VIN`} value={row.sourceIdentifier} onChange={(event) => updateBatchRow(index, "sourceIdentifier", event.target.value)} placeholder="Stock # or VIN" /><button aria-label={`Remove row ${index + 1}`} className="remove-batch-row" type="button" onClick={() => removeBatchRow(index)}>×</button></div>)}</div><button className="add-batch-row" type="button" onClick={() => setBatchRows((rows) => [...rows, ...blankBatchRows(1)])}>+ Add another vehicle</button><button className="primary" type="submit">Build verification queue</button></form></div>}
    {verificationOpen && <div className="backdrop"><section className="intake verification-card"><button aria-label="Close verification queue" type="button" className="close" onClick={() => setVerificationOpen(false)}>×</button><p className="eyebrow">PO / RO VERIFICATION</p><h2>Review, approve, print.</h2><p>Ready rows are unique matches. Review rows stay separate until you enter them manually—nothing uncertain is attached.</p><div className="verification-actions"><button className="primary" type="button" onClick={() => void approveReadyMatches()} disabled={!verificationItems.some((item) => item.status === "ready")}>Approve all ready matches</button><button className="secondary" type="button" onClick={printVerificationQueue}>Print verification queue</button></div><div className="verification-list">{verificationItems.filter((item) => item.status !== "skipped").map((item) => <article key={item.id} className={`verification-item ${item.status}`}><div><span className="verification-status">{item.status === "ready" ? "Ready" : item.status === "needs_review" ? "Review" : "Attached"}</span><strong>PO {item.purchaseOrderNumber}{item.repairOrderNumber ? ` · RO ${item.repairOrderNumber}` : ""}</strong><small>Entered: {item.sourceIdentifier} · {item.matchMethod}</small><small>{item.matchedJob ? `Vehicle: ${item.matchedJob.stockOrVin}${item.matchedJob.vehicle ? ` · ${item.matchedJob.vehicle}` : ""}` : item.candidateJobIds.length ? `${item.candidateJobIds.length} possible vehicle match${item.candidateJobIds.length === 1 ? "" : "es"}` : "No eligible completed vehicle found"}</small></div>{item.status === "ready" && <button className="primary" type="button" onClick={() => void reviewVerificationItem(item.id, "approve")}>Approve</button>}{item.status === "needs_review" && <div className="verification-item-actions"><button className="history" type="button" onClick={() => { setVerificationOpen(false); openManager(); }}>Enter manually</button><button className="history" type="button" onClick={() => void reviewVerificationItem(item.id, "skip")}>Remove</button></div>}</article>)}{!verificationItems.filter((item) => item.status !== "skipped").length && <p className="empty">No PO rows are waiting for verification.</p>}</div></section></div>}
    {historyOpen && <div className="backdrop"><section className="intake audit-card"><button aria-label="Close history" type="button" className="close" onClick={() => setHistoryOpen(false)}>×</button><p className="eyebrow">AUDIT HISTORY</p><h2>{historyJob?.stockOrVin}</h2><p>Every recorded entry and PO / RO correction for this job.</p><div className="audit-events">{auditEvents.map((event) => <article key={event.id}><strong>{event.eventType}</strong><time>{new Date(event.createdAt).toLocaleString([], { dateStyle: "medium", timeStyle: "short" })}</time><small>{event.actorName || event.actorEmail}</small>{event.reason && <p>Reason: {event.reason}</p>}</article>)}{!auditEvents.length && <p className="empty">Loading recorded history…</p>}</div></section></div>}
    {cameraOpen && <div className="backdrop camera-backdrop"><section className="camera-card"><button aria-label="Close camera" type="button" className="close" onClick={() => setCameraOpen(false)}>×</button><p className="eyebrow">VIN CAMERA SCANNER</p><h2>Frame the door-jamb barcode.</h2><p>Hold the phone steady and keep the full barcode inside the guide. The VIN fills in automatically.</p><div className="camera-frame"><video ref={videoRef} muted playsInline /><span /></div>{cameraError && <p className="camera-error">{cameraError} Use manual VIN entry on this device.</p>}<button type="button" className="secondary" onClick={() => setCameraOpen(false)}>Cancel</button></section></div>}
    {intakeOpen && <div className="backdrop"><form className="intake quick-intake" onSubmit={saveJob}><button aria-label="Close" type="button" className="close" onClick={() => setIntakeOpen(false)}>×</button><p className="eyebrow">{view === "technician" ? "QUICK COMPLETE" : "NEW COMPLETED JOB"}</p><h2>{view === "technician" ? "Scan, select, finish." : "Record the job once."}</h2><p>{view === "technician" ? "Your name is automatic and this device remembers its location." : "The timestamp is the job identity, so repeat stock numbers are allowed."}</p><label>Location<select value={locationId === "all" ? "" : locationId} onChange={(e) => setLocationId(Number(e.target.value))} required><option value="">Choose location</option>{locations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>{view === "technician" ? "Signed-in technician" : "Your name"}<input required readOnly={view === "technician"} value={technicianName} onChange={(e) => setTechnicianName(e.target.value)} placeholder="Technician name" /></label><label className="vehicle-scan">1. Scan VIN or enter stock number<div className="scan-input"><input autoFocus required autoCapitalize="characters" value={stock} onChange={(e) => setStock(normalizeVehicleId(e.target.value))} placeholder="Scan the door-jamb barcode" /><button type="button" onClick={() => { setCameraError(""); setCameraOpen(true); }}>Open camera</button></div></label><fieldset className="service-picker"><legend>2. Select the service</legend>{BASE_SERVICE_OPTIONS.map((service) => <label key={service}><input type="radio" name="detail-service" checked={selectedServices.includes(service)} onChange={() => chooseBaseService(service)} />{service}</label>)}<label><input type="checkbox" checked={selectedServices.includes(APPEARANCE_PROTECTION)} onChange={toggleAppearanceProtection} />{APPEARANCE_PROTECTION}</label></fieldset><details className="optional-details"><summary>Vehicle and damage notes <span>(optional)</span></summary><label>Vehicle<input value={vehicle} onChange={(e) => setVehicle(e.target.value)} placeholder="2026 Honda CR-V" /></label><label>Damage notes<textarea value={damageNotes} onChange={(e) => setDamageNotes(e.target.value)} placeholder="Describe any damage noticed before or during the detail." rows={3} /></label></details><button className="primary" type="submit">{view === "technician" ? "Complete vehicle" : "Save timestamped job"}</button></form></div>}
  </main>;
}

function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <article><p>{label}</p><strong>{value}</strong><small>{note}</small></article>; }

function LoginScreen({ onSignedIn }: { onSignedIn: (member: Member) => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const response = await fetch("/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await response.json().catch(() => null) as { member?: Member; error?: string } | null; setSaving(false); if (!response.ok || !data?.member) { setError(data?.error ?? "Sign-in is not available right now."); return; } onSignedIn(data.member); }
  return <main className="sign-in-shell"><section className="sign-in-card"><div className="brand"><b>T</b><span>Titan Operations</span></div><p className="eyebrow">STAFF SIGN-IN</p><h1>Start your shift.</h1><p>Use the email and password provided by your manager.</p><form onSubmit={submit}><label>Email<input autoFocus required type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" /></label><label>Password<input required type="password" autoComplete="current-password" minLength={8} maxLength={128} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Your password" /></label>{error && <p className="login-error">{error}</p>}<button className="primary" type="submit" disabled={saving}>{saving ? "Signing in…" : "Sign in"}</button></form></section></main>;
}
