import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const locations = sqliteTable("locations", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull().unique(), active: integer("active", { mode: "boolean" }).notNull().default(true) });
export const members = sqliteTable("members", { email: text("email").primaryKey(), displayName: text("display_name").notNull().default(""), role: text("role", { enum: ["manager", "technician"] }).notNull(), active: integer("active", { mode: "boolean" }).notNull().default(true) });
export const memberCredentials = sqliteTable("member_credentials", { email: text("email").primaryKey(), pinHash: text("pin_hash").notNull(), createdAt: text("created_at").notNull() });
export const authSessions = sqliteTable("auth_sessions", { id: text("id").primaryKey(), tokenHash: text("token_hash").notNull().unique(), email: text("email").notNull(), expiresAt: text("expires_at").notNull(), createdAt: text("created_at").notNull() });
export const poVerificationItems = sqliteTable("po_verification_items", { id: text("id").primaryKey(), createdAt: text("created_at").notNull(), sourceLine: text("source_line").notNull(), sourceIdentifier: text("source_identifier").notNull(), purchaseOrderNumber: text("purchase_order_number").notNull(), repairOrderNumber: text("repair_order_number"), matchedJobId: text("matched_job_id"), candidateJobIds: text("candidate_job_ids").notNull().default("[]"), matchMethod: text("match_method").notNull(), status: text("status", { enum: ["ready", "needs_review", "approved", "skipped"] }).notNull(), enteredByEmail: text("entered_by_email").notNull().default(""), reviewedAt: text("reviewed_at") });
export const jobs = sqliteTable("jobs", { id: text("id").primaryKey(), locationId: integer("location_id").notNull(), completedAt: text("completed_at").notNull(), stockOrVin: text("stock_or_vin").notNull(), vehicle: text("vehicle").notNull().default(""), technicianName: text("technician_name").notNull().default(""), damageNotes: text("damage_notes").notNull().default(""), service: text("service").notNull(), baseAmount: integer("base_amount").notNull(), addOnAmount: integer("add_on_amount").notNull(), purchaseOrderNumber: text("purchase_order_number"), repairOrderNumber: text("repair_order_number"), purchaseOrderUrl: text("purchase_order_url"), archiveUrl: text("archive_url") });
export const jobAuditEvents = sqliteTable("job_audit_events", { id: text("id").primaryKey(), jobId: text("job_id").notNull(), createdAt: text("created_at").notNull(), eventType: text("event_type").notNull(), actorEmail: text("actor_email").notNull().default(""), actorName: text("actor_name").notNull().default(""), reason: text("reason"), beforeValue: text("before_value"), afterValue: text("after_value").notNull() });

// Weekly invoice packets submitted to the dealership. A packet covers one or more completed,
// PO'd jobs from a single location. Paid once a payment (check) is recorded against it.
export const invoices = sqliteTable("invoices", { id: text("id").primaryKey(), locationId: integer("location_id").notNull(), periodStart: text("period_start").notNull(), periodEnd: text("period_end").notNull(), status: text("status", { enum: ["submitted", "paid"] }).notNull().default("submitted"), submittedAt: text("submitted_at").notNull(), createdByEmail: text("created_by_email").notNull().default(""), paymentId: text("payment_id") });

// A single dealership check. One check commonly pays several invoices at once, so this is a
// one-to-many relationship: invoices.paymentId points here once the invoice is marked paid.
export const payments = sqliteTable("payments", { id: text("id").primaryKey(), receivedAt: text("received_at").notNull(), checkNumber: text("check_number").notNull(), amount: integer("amount").notNull(), notes: text("notes").notNull().default(""), recordedByEmail: text("recorded_by_email").notNull().default("") });

// Join table: which completed jobs a given invoice covers. jobId is unique so a job can never
// be billed on more than one invoice.
export const invoiceJobs = sqliteTable("invoice_jobs", { id: text("id").primaryKey(), invoiceId: text("invoice_id").notNull(), jobId: text("job_id").notNull().unique() });
